name: TER

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.1

      - name: Install requirements
        run: composer global require --dev helhum/ter-client dev-master

      - name: Cleanup before we upload
        run: git reset --hard HEAD && git clean -fx

      - name: Build extension files
        run: composer extension-release

      - name: Publish to TER
        run: |
          TAG_MESSAGE=`git tag -n10 -l $(git describe --tags) | sed 's/^[0-9.]*[ ]*//g'`
          ech $TAG_MESSAGE
